version: '3.1'

services:
  mongo:
    image: mongo
    container_name: my-mongo
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

  server:
    image: node:16
    container_name: my-server
    working_dir: /usr/src/app/server
    volumes:
      - ./server:/usr/src/app/server
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://admin:password@mongo:27017
    command: bash -c "npm install && npx tsc && node server.js"

volumes:
  mongodata:
